// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Un4qe1SEzIjwPDtAJdLK0WgjBU-An-A',
    appId: '1:558930400943:web:01b56dccb1a72b94b8e65a',
    messagingSenderId: '558930400943',
    projectId: 'app-fire-394da',
    authDomain: 'app-fire-394da.firebaseapp.com',
    databaseURL: 'https://app-fire-394da-default-rtdb.firebaseio.com',
    storageBucket: 'app-fire-394da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhR6nbJ-mSEtyPJ2ZH7mvnO2uHay9Nb4E',
    appId: '1:558930400943:android:dc2e513199595b29b8e65a',
    messagingSenderId: '558930400943',
    projectId: 'app-fire-394da',
    databaseURL: 'https://app-fire-394da-default-rtdb.firebaseio.com',
    storageBucket: 'app-fire-394da.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Un4qe1SEzIjwPDtAJdLK0WgjBU-An-A',
    appId: '1:558930400943:web:d0708be035bbd877b8e65a',
    messagingSenderId: '558930400943',
    projectId: 'app-fire-394da',
    authDomain: 'app-fire-394da.firebaseapp.com',
    databaseURL: 'https://app-fire-394da-default-rtdb.firebaseio.com',
    storageBucket: 'app-fire-394da.firebasestorage.app',
  );

}